---
title: "Clustering for Production, Consumption of Primary Energy"
author: "Stella Lee"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(rvest)
library(stringr)
library(readr)
library(ggplot2)
library(tidyr)
library(factoextra)
library(gridExtra)
library(tidyverse)
library(cluster)
# This is data processing for clustering. 
cols <- c ("1980","1981","1982","1983","1984","1985","1986","1987","1988","1989",
           "1990","1991","1992","1993","1994","1995","1996","1997","1998","1999",
           "2000","2001","2002","2003","2004","2005","2006","2007","2008","2009",
           "2010","2011","2012","2013","2014","2015","2016")
colsn <- (1980:2016)

# This function is used for dropping unneccesary column and set the column names----
set <- function(data){
  data <- data [-c(1,3)]
  names(data) <- c("country",
                   "1980","1981","1982","1983","1984","1985","1986","1987","1988","1989",
                   "1990","1991","1992","1993","1994","1995","1996","1997","1998","1999",
                   "2000","2001","2002","2003","2004","2005","2006","2007","2008","2009",
                   "2010","2011","2012","2013","2014","2015","2016")
  
  for (col in cols){
    data[,col] <- as.numeric(as.character(data[,col]))
    data[,col] <- (10^15 * data[,col])
  }
  data
}

# Data----
# Dataframe for production of primary energy by country from 1980 to 2016 (unit: quad btu)
production <- read.csv("https://raw.githubusercontent.com/stellasylee/Energy/master/International_data_energy.csv", 
                       skip = 8, nrows = 228, head = FALSE) %>%
  set(.)

# Dataframe for consumption of primary energy by country from 1980 to 2016 (unit: quad btu)
consumption <- read.csv("https://raw.githubusercontent.com/stellasylee/Energy/master/International_data_energy.csv",
                        skip = 238, head = FALSE) %>%
  set(.)


# Population data from 1980 to 2016
worldBank <- function (data){
  data <- data [,-(1:2)] %>% .[,-2]
  names (data) <- c("country", cols)
  # Modify country names to match with production and consumption data
  data$country <- as.character(data$country)
  data$country[33] <- "Cape Verde"
  data$country[136] <- "Burma (Myanmar)"
  data$country[45] <- "Congo (Kinshasa)"
  data$country[46] <- "Congo (Brazzaville)"
  data$country[59] <- "Egypt"
  data$country[87] <- "Hong Kong"
  data$country[104] <- "Korea, North"
  data$country[105] <- "Korea, South"
  data$country[109] <- "Laos"
  data$country[118] <- "Macau"
  data$country[146] <- "Macedonia"
  data$country[140] <- "Netherlands"
  data$country[162] <- "Russia"
  data$country[64] <- "Swaziland"
  data$country[213] <- "Virgin Islands, U.S."
  data$country[28] <- "Virgin Islands, British"
  data$country[215] <- "Yemen"
  
  data
}
population <- read.csv("https://raw.githubusercontent.com/stellasylee/Energy/master/worldPopulation.csv") %>%
  worldBank(.)

ppp <- read.csv("https://raw.githubusercontent.com/stellasylee/Energy/master/worldPPP.csv") %>%
  worldBank(.)
ppp[ppp == "" | ppp == ".."] <- NA

# Join the data (intersection)
# Combine Germany East, West to Germany
for (i in (1980:1990)){
  production[78,paste(i)] <- production[79,paste(i)] + production[80,paste(i)]
  consumption[78,paste(i)] <- consumption[79,paste(i)] + consumption[80,paste(i)] 
}
production$country <- as.character(production$country)
consumption$country <- as.character(consumption$country)

sortByCountry <- function (data){
  data <- data[order(data$country),]
  row.names(data) <- c(1:191)
  data
} 

cleanedPro <- dplyr::filter(production, !(production$country %in% anti_join(x = production, y = population, by = "country")$country)) %>%
  sortByCountry (.)
cleanedCon <- dplyr::filter(consumption, !(consumption$country %in% anti_join(x = consumption, y = population, by = "country")$country))%>%
  sortByCountry (.)
cleanedPop <- dplyr::filter(population, !(population$country %in% anti_join(x = population, y = production, by = "country")$country))%>%
  sortByCountry (.)
cleanedPPP <- dplyr::filter(ppp, !(ppp$country %in% anti_join(x = ppp, y = production, by = "country")$country)) %>%
  sortByCountry (.)


for (i in 2:38){
  cleanedPop[,i] <- parse_number(as.character(cleanedPop[,i]))
  cleanedPPP[,i] <- parse_number(as.character(cleanedPPP[,i]))
}

# World Average
world <- cbind(x = as.data.frame(colSums(cleanedPro[,-1], na.rm = TRUE)), # production
               y = as.data.frame(colSums(cleanedCon[,-1], na.rm = TRUE))) # consumption
worldPop <- as.data.frame(colSums(cleanedPop[,-1], na.rm = TRUE))
for (i in (1:37)){
  world[i,1] <- as.numeric(world[i,1]) / as.numeric(worldPop[i,1]) # world avg production
  world[i,2] <- as.numeric(world[i,2]) / as.numeric(worldPop[i,1]) # world avg consumption
}
names(world)<- c("worldPro", "worldCon")
```

# Compare 2016 vs 1990 Clustering
##2016: 
```{r}
combine16 <- as.data.frame(cbind(cleanedPro[,38], cleanedCon[,38], cleanedPPP[,38], cleanedPop[,38]))
names(combine16) <- c("pro","con","ppp","pop")
row.names(combine16) <- cleanedPro$country
combine16 <- combine16[complete.cases(combine16),]
cluster16 <- as.data.frame(scale(combine16[,-4])) 
# Find optimal number of centers 
fviz_nbclust(cluster16, kmeans, method = "wss", k.max = 8)

# k-means method
k2 <- kmeans(cluster16, centers = 2, nstart = 25)
fviz_cluster(k2, data = cluster16)
grid.arrange(
  fviz_cluster(k2, data = cluster16),
  fviz_cluster(k2, data = cluster16, choose.vars = c("pro", "con"), geom = "point"),
  fviz_cluster(k2, data = cluster16, choose.vars = c("pro", "ppp"), geom = "point"),
  fviz_cluster(k2, data = cluster16, choose.vars = c("con", "ppp"), geom = "point"),
  ncol=2, top="k-means clustering of 2016")
```

## 2019:
```{r}
combine90 <- as.data.frame(cbind(cleanedPro[,12], cleanedCon[,12], cleanedPPP[,12], cleanedPop[,12]))
names(combine90) <- c("pro","con","ppp","pop")
row.names(combine90) <- cleanedPro$country
combine90 <- combine90[complete.cases(combine90),]

cluster90 <- as.data.frame(scale(combine90[,-4])) 
# Find optimal number of centers 
fviz_nbclust(cluster90, kmeans, method = "wss", k.max = 8)

# k-means method
k2 <- kmeans(cluster90, centers = 2, nstart = 25)
fviz_cluster(k2, data = cluster90)
grid.arrange(
  fviz_cluster(k2, data = cluster90),
  fviz_cluster(k2, data = cluster90, choose.vars = c("pro", "con"), geom = "point"),
  fviz_cluster(k2, data = cluster90, choose.vars = c("pro", "ppp"), geom = "point"),
  fviz_cluster(k2, data = cluster90, choose.vars = c("con", "ppp"), geom = "point"),
  ncol=2, top="k-means clustering of 1990")
```

# Compare per Capita data
## 2016: 
```{r}
perCap16 <- combine16
for (i in (1:175)){
  perCap16[i,1] <- as.numeric(perCap16[i,1]) / as.numeric(perCap16[i,4]) 
  perCap16[i,2] <- as.numeric(perCap16[i,2]) / as.numeric(perCap16[i,4]) 
  perCap16[i,3] <- as.numeric(perCap16[i,3]) / as.numeric(perCap16[i,4]) 
}

# We have to scale because Purchasing Power Parity has different unit
perCap16 <- as.data.frame(scale(perCap16[,-4])) 
perCap16 <- perCap16[apply(perCap16, 1, function(x) all(is.finite(x))), ]

# Find optimal number of centers 
fviz_nbclust(perCap16, kmeans, method = "wss", k.max = 8)

# k-means method
k2 <- kmeans(perCap16, centers = 2, nstart = 25)
fviz_cluster(k2, data = perCap16)
grid.arrange(
  fviz_cluster(k2, data = perCap16),
  fviz_cluster(k2, data = perCap16, choose.vars = c("pro", "con"), geom = "point"),
  fviz_cluster(k2, data = perCap16, choose.vars = c("pro", "ppp"), geom = "point"),
  fviz_cluster(k2, data = perCap16, choose.vars = c("con", "ppp"), geom = "point"),
  ncol=2, top="k-means clustering of 2016 per captia")
```

```{r}
k3 <- kmeans(perCap16, centers = 3, nstart = 25)
grid.arrange(
  fviz_cluster(k3, data = perCap16),
  fviz_cluster(k3, data = perCap16, choose.vars = c("pro", "con"), geom = "point"),
  fviz_cluster(k3, data = perCap16, choose.vars = c("pro", "ppp"), geom = "point"),
  fviz_cluster(k3, data = perCap16, choose.vars = c("con", "ppp"), geom = "point"),
  ncol=2, top="k-means clustering of 2016 per captia (3 centers)")
```

1990:
```{r}
perCap90 <- combine90

for (i in (1:191)){
  perCap90[i,1] <- as.numeric(perCap90[i,1]) / as.numeric(perCap90[i,4]) 
  perCap90[i,2] <- as.numeric(perCap90[i,2]) / as.numeric(perCap90[i,4]) 
  perCap90[i,3] <- as.numeric(perCap90[i,3]) / as.numeric(perCap90[i,4]) 
}
perCap90 <- perCap90[complete.cases(perCap90),]
perCap90 <- as.data.frame(scale(perCap90[,-4]))
# Find optimal number of centers
fviz_nbclust(perCap90, kmeans, method = "wss", k.max = 8)
#fviz_nbclust(perCap90, kmeans, method = "silhouette", k.max = 8)
k2 <- kmeans(perCap90, centers = 2, nstart = 25)
fviz_cluster(k2, data = perCap90)
grid.arrange(
  fviz_cluster(k2, data = perCap90),
  fviz_cluster(k2, data = perCap90, choose.vars = c("pro", "con"), geom = "point"),
  fviz_cluster(k2, data = perCap90, choose.vars = c("pro", "ppp"), geom = "point"),
  fviz_cluster(k2, data = perCap90, choose.vars = c("con", "ppp"), geom = "point"),
  ncol=2, top="k-means clustering of 1990 per captia")
```